export { default as Header } from './Header';
export {default as AllPosts } from  './AllPosts';
export {default as LoginPage } from  './LoginPage';
export {default as SearchBar } from  './SearchBar';
export {default as SinglePostView } from  './SinglePostView';
export {default as RegisterUser } from  './RegisterUser';
export {default as Profile } from  './Profile';
export {default as Home } from  './Home';
export {default as EditPost } from  './EditPost';
export {default as AddNewPost } from  './AddNewPost';
export {default as SendMessageView } from  './SendMessageView';